---
- name: Manage Infrastructure 
  hosts: localhost
  gather_facts: False
  roles:
    - role: rackspace
      networks:
        - name: "{{env}}-dmz"
          cidr: "192.168.2.0/24"
        - name: "{{env}}-private"
          cidr: "192.168.3.0/24"
      nodes:
        - count: 3
          group: "{{env}}-master"
          networks:
            - public
            - private
            - "{{env}}-dmz"
            - "{{env}}-private"
        - count: 3
          group: "{{env}}-slave"
          networks:
            - public
            - private
            - "{{env}}-dmz"
            - "{{env}}-private"
            
- name: Bootstrap CoreOS
  hosts: 
    - "{{env}}-master"
    - "{{env}}-slave"
  gather_facts: False
  roles:
    - sigma.coreos-bootstrap

- name: Config Master Nodes    
  hosts: "{{env}}-master"
  roles:
    - master


- name: Config Slave Nodes
  hosts: "{{env}}-slave"
  roles:
    - slave


