---
- name: Manage master nodes
  hosts: localhost
  gather_facts: False
  vars:
    region: LON
    exact_count: true
    flavor: 4
    image: 40155f16-21d4-4ac1-ad65-c409d94b8c7c
    key_name: "{{keyname}}"
    state: present
  roles:
      - { role: rackspace, count: 3, group: "{{env}}-master" }

- name: Manage slave nodes
  hosts: localhost
  gather_facts: False
  vars:
    region: LON
    exact_count: true
    flavor: 4
    image: 40155f16-21d4-4ac1-ad65-c409d94b8c7c
    key_name: "{{keyname}}"
    state: present
  roles:
      - { role: rackspace, count: 3, group: "{{env}}-slave" }


- hosts:
    - "{{env}}-master"
    - "{{env}}-slave"
  gather_facts: False
  roles:
    - sigma.coreos-bootstrap
