---
- name: Manage Infrastructure 
  hosts: localhost
  gather_facts: False
  roles:
    - role: rackspace
      networks:
        - name: "{{env}}-network"
          cidr: "192.168.3.0/24"
      nodes:
        - count: 3
          group: "{{env}}-master"
        - count: 3
          group: "{{env}}-slave"

- hosts: 
    - "{{env}}-master"
    - "{{env}}-slave"
  gather_facts: False
  roles:
    - sigma.coreos-bootstrap

- hosts: "{{env}}-master"
  roles:
    - master

- hosts: "{{env}}-slave"
  roles:
    - slave


