---

- hosts: localhost
  gather_facts: False
  vars:
    region: LON
    count: 6
    exact_count: true
    flavor: 4
    image: 40155f16-21d4-4ac1-ad65-c409d94b8c7c
    key_name: dianya
    state: present
  roles:
    - rackspace

- hosts: "{{group}}"
  gather_facts: False
  roles:
    - sigma.coreos-bootstrap
